<?php

namespace Database\Seeders;

use App\Models\MasterMitra;
use Illuminate\Database\Seeder;

class AssignKodeMitraSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['A01', 'ALIANSI JURNALIS INDEPENDEN (AJI) KOTA BATAM'],
            ['A02', 'Aerocampus Aquitaine'],
            ['A03', 'Akademi Komunitas Industri Manufaktur Bantaeng'],
            ['A04', 'Akademi Komunitas Negeri (AKN) Putra Sang Fajar Blitar'],
            ['A05', 'Akademi Melayu Dermawan'],
            ['A06', 'Al-Ahmadi Enterpreneur Center'],
            ['A07', 'Apotik Mafaza'],
            ['A08', 'Asosiasi Logistik & Forwarder Indonesia (ALFI) DPW Jateng Dan DIY'],
            ['A09', 'Asosiasi Logistik & Forwarder Indonesia (ALFI) DPW Jawa Timur'],
            ['A10', 'Asosiasi Konsultan Pajak Publik Indonesia (AKP2I)'],
            ['A11', 'Asosiasi Logistik Indonesia (ALI) Chapter Batam'],
            ['A12', 'Asosiasi Pelaku Pariwisata Indonesia (ASPPI) DPD Kepri'],
            ['A13', 'Asosiasi Pendidikan Tinggi Informatika Dan Komputer'],
            ['A14', 'ASOSIASI PENGURUS PELAKSANA KONTRAKTOR DAN KONTRUKSI NASIONAL (APPEKNAS) DEWAN PENGURUS NASIONAL (DPN)'],
            ['A15', 'Asosiasi Penyelenggara Jasa Internet Indonesia (APJII)'],
            ['A16', 'Asosiasi Perusahaan Jasa Pengiriman Ekspres, Pos, Dan Logistik Indonesia (ASPERINDO)'],
            ['A17', 'Asosiasi Tenaga Ahli Kepabeanan (ATAK) Batam'],
            ['B1',  'Base Incubator'],
            ['B2',  'Batam Aero Technic'],
            ['B3',  'BPJS Ketenagakerjaan'],
            ['BA01', 'Bank BTN Syariah'],
            ['BA02', 'PT Bank Negara Indonesia (Persero) Tbk'],
            ['BA03', 'PT Bank Mandiri (Persero) Tbk'],
            ['BA04', 'PT Bank Rakyat Indonesia (Persero)'],
            ['BA05', 'PT Bank Tabungan Negara (Persero) Tbk'],
            ['BA06', 'PT BPR Pekanbaru Madani (Perseroda)'],
            ['BA07', 'PT Bank KB Indonesia Tbk'],
            ['BA08', 'Bank Indonesia'],
            ['BD01', 'Badan Riset dan Inovasi Nasional (BRIN)'],
            ['BD02', 'BADAN PELINDUNGAN PEKERJA MIGRAN INDONESIA (BP2MI)'],
            ['BD03', 'Badan Informasi Geospasial'],
            ['BD04', 'Badan Narkotika Nasional Provinsi Kepulauan Riau'],
            ['BD05', 'Badan Pendapatan Daerah Kota Batam'],
            ['BD06', 'Badan Pengawas Pemilihan Umum Provinsi Kepulauan Riau'],
            ['BD07', 'Badan Pengelolaan Pajak Dan Restribusi Daerah'],
            ['BD08', 'Badan Pengusahaan Kawasan Perdagangan Bebas Dan Pelabuhan Bebas Batam (BP Batam)'],
            ['BD09', 'Badan Penyelenggara Jaminan Produk Halal (BPJPH)'],
            ['BD10', 'Badan Pusat Statistik Provinsi Kepulauan Riau'],
            ['BD11', 'Badan Syber Dan Sandi Negara Republik Indonesia'],
            ['BD12', 'Badan Usaha Milik Desa Bersama Mahkota Bunguran Utara Abadi'],
            ['BD13', 'Badan Pengembangan Sumber Daya Manusia Aceh'],
            ['BL01', 'BALAI JASA KONSTRUKSI WILAYAH I BANDA ACEH DIREKTORAT JENDERAL BINA KONSTRUKSI KEMENTERIAN PEKERJAAN UMUM DAN PERUMAHAN RAKYAT'],
            ['BL02', 'Balai Pengelolaan Pengujian Pendidikan Kementerian Pendidikan, Kebudayaan, Riset Dan Teknologi'],
            ['BL03', 'BALAI LABORATORIUM KESEHATAN MASYARAKAT BATAM KEMENTERIAN KESEHATAN REPUBLIK INDONESIA'],
            ['CV01', 'CV Sindikat Otak Kanan'],
            ['CV02', 'CV Wesley Sukses Abadi'],
            ['CV03', 'CV Amanah Berkah Bersama'],
            ['CV04', 'CV Berkah Gazza Sukses'],
            ['CV05', 'CV Carbonex Solusi'],
            ['CV06', 'CV Danar Utama'],
            ['CV07', 'CV Ebony Karya Mandiri'],
            ['CV08', 'CV Multi Art Project (Senja Group)'],
            ['CV09', 'CV Multi Kreasindo Mandiri (Arial Studio)'],
            ['D01', 'Dinas Pendidikan Provinsi Kepulauan Riau'],
            ['D02', 'Dinas Komunikasi dan Informatika Kota Batam'],
            ['D03', 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk dan KB Kota Batam (DP3AP2KB)'],
            ['D04', 'Dinas Energi dan Sumber Daya Mineral'],
            ['D05', 'Dinas Perumahan, Kawasan Permukiman Dan Pertamanan Kota Batam (Perkimtan)'],
            ['D06', 'Direktorat Akademik Pendidikan Tinggi Vokasi'],
            ['D07', 'Direktorat Pembelajaran dan Kemahasiswaan'],
            ['D08', 'Direktorat Jenderal Pengelolaan Pembiayaan Dan Risiko'],
            ['D09', 'Direktorat Jenderal Aplikasi dan Informatika, Kementerian Komunikasi dan Informatika'],
            ['D10', 'Direktorat Jenderal Kerjasama Asean'],
            ['D11', 'Direktorat Jenderal Pendidikan Vokasi'],
            ['D12', 'Dewan Pimpinan Daerah Forum Pengelola Lembaga Kursus & Pelatihan Provinsi Kepulauan Riau'],
            ['E01', 'Ekspedisi Lion Parcel Taras'],
            ['F01', 'Forum Human Capital Indonesia'],
            ['F02', 'Forum Lembaga Pelatihan Vokasi Indonesia Provinsi Kepulauan Riau'],
            ['H01', 'Himpunan Lembaga Pelatihan Seluruh Indonesia Kepulauan Riau (HILLSI)'],
            ['H02', 'Himpunan Pengusaha Muda Indonesia Perguruan Tinggi Kepulauan Riau'],
            ['H03', 'Himpunan Kawasan Industri (HKI) Kepulauan Riau'],
            ['I01', 'Ikatan Alumni Institut Teknologi Bandung'],
            ['I02', 'Ikatan Alumni Institut Teknologi Sepuluh Nopember Kepulauan Riau'],
            ['I03', 'Ikatan Alumni Universitas Diponegoro'],
            ['I04', 'Indonesian Diaspora Network Global (IDN-Global)'],
            ['I05', 'Ikatan Akuntan Indonesia Wilayah Kepulauan Riau'],
            ['I06', 'Institut Informatika Dan Bisnis Darmajaya'],
            ['I07', 'Institut Teknologi Dan Bisnis Indobaru Nasional'],
            ['I08', 'Institut Teknologi Bandung'],
            ['I09', 'Institut Teknologi Dirgantara Adisutjipto (ITDA)'],
            ['I10', 'Institut Teknologi Batam'],
            ['I11', 'Institut Teknologi Perkebunan Pelalawan Indonesia (ITP2I)'],
            ['I12', 'Institut Teknologi Sepuluh Nopember (ITS)'],
            ['I13', 'International Talent Circulation Base (Taiwan - Indonesia)'],
            ['I14', 'Ikatan Teknisi Rekayasa & Ahli Teknologi Rekayasa Indonesia (ITERATI)'],
            ['I15', 'Institut Teknologi Sumatera (ITERA)'],
            ['J01', 'Jaringan Safe Migrant Batam'],
            ['K01', 'Kejaksaan Negeri Batam'],
            ['K02', 'Komisi Nasional Disabilitas'],
            ['K03', 'Komunitas Game Developer Batam'],
            ['K04', 'Komunitas Pengusaha Tangan Di Atas (Tda) Kota Batam'],
            ['K05', 'Koperasi Jasa Kreasi Dinamika Harmoni'],
            ['K06', 'Koperasi Konsumen Politeknik Negeri Batam'],
            ['K07', 'Koperasi Rumah Bungkus Radja Isha'],
            ['K08', 'Klinik Utama Spesialis Biostem'],
            ['K09', 'Kelompok Sadar Wisata (Pokdarwis) Pandang Tak Jemu'],
            ['KA01', 'Kantor Akuntan Publik Hendrawinata Hanny Erwin & Sumargo'],
            ['KA02', 'Kantor Bahasa Provinsi Kepulauan Riau'],
            ['KA03', 'Kantor Wilayah Badan Pertanahan Nasional Provinsi Kepulauan Riau'],
            ['KA04', 'Kantor Wilayah DJP Kepulauan Riau'],
            ['KA05', 'Kantor Wilayah Kementerian Agama Provinsi Kepulauan Riau'],
            ['KA06', 'Kantor Wilayah Kementerian Hukum Kepulauan Riau'],
            ['L01', 'Lembaga Pengkajian Pangan, Obat-Obatan, Dan Kosmetika Majelis Ulama Indonesia (LPPOM MUI)'],
            ['L02', 'Lembaga Multi Kompetensi Utama'],
            ['L03', 'Lembaga Keterampilan Profesi Logistik Indonesia (LKP Login)'],
            ['L04', 'LKP Silhouette Training Centre Dan CV Silhouette Internasional'],
            ['L05', 'Lembaga Pelatihan Kerja Sembilan Tara Nawasena (LPK Nawasena)'],
            ['L06', 'Lembaga Penyiaran Publik Radio Republik Indonesia'],
            ['L07', 'Lembaga Penyiaran Publik TVRI Stasiun Riau'],
            ['L08', 'Lembaga Sertifikasi Profesi Geomatika'],
            ['L09', 'Lembaga Sertifikasi Profesi Otomasi Mekatronika Indonesia (OMI)'],
            ['L10', 'Lembaga Sertifikasi Profesi Survey Pemetaan Isi'],
            ['L11', 'LSP PERPAJAKAN INDONESIA'],
            ['LA01', 'Association of Chartered Certified Accountants (ACCA)'],
            ['LA02', 'AERAE HOLDINGS LTD.'],
            ['LB01', 'B2B Success. CO., Ltd'],
            ['LB02', 'Bharatiya Engineering Science And Technology Innovation University'],
            ['LB03', 'Baekseok University Of Republic Of Korea'],
            ['LC01', 'Cap Advisory Group PTE. LTD .'],
            ['LC02', 'Catanduanes State University'],
            ['LC03', 'Cebu Technological University'],
            ['LC04', 'Cheng Shiu University'],
            ['LC05', 'Chongqing College Of Electronic Engineering'],
            ['LC06', 'Chung Yuan Christian University'],
            ['LC07', 'City Of Glassgow College'],
            ['LG01', 'Gempacs'],
            ['LG02', 'Guandong Mechanical & Electrical Polytechnic'],
            ['LG03', 'Guangxi Polytechnic Of Construction'],
            ['LH01', 'HOPE International Economic Cooperation (Wuhan) Co., Ltd.'],
            ['LK01', 'KAMK University, Finland'],
            ['LK02', 'Kolej Komuniti Segamat Johor, Malaysia'],
            ['LK03', 'Kolej Komuniti Bukit Beruang'],
            ['LL01', 'Lembaga Hasil Dalam Negeri (LHDN) Malaysia'],
            ['LL02', 'Liuzhou Polytechnic University'],
            ['LL03', 'Lunghwa University Of Science And Technology'],
            ['LL04', 'PT Liugong Machinery Indonesia'],
            ['LM01', 'Management And Science University, Malaysia'],
            ['LM02', 'Ming Chi University Of Technology'],
            ['LM03', 'Monash University'],
            ['LM04', 'Med Technologies PTE LTD'],
            ['LM05', 'Minjiang Teachers College'],
            ['LN01', 'Nanyang Polytechnic, Singapore'],
            ['LN02', 'National Chin-Yi University Of Technology'],
            ['LN03', 'National Taichung University Of Education (Taiwan)'],
            ['LN04', 'National Yunlin University Of Science And Technology'],
            ['LN05', 'Norwegian University Of Science And Technology'],
            ['LN06', 'Nueva Ecija University Of Science And Technology'],
            ['LP01', 'Pangasinan State University'],
            ['LP02', 'Parallaxnet Llc'],
            ['LP03', 'Politeknik Sultan Salahuddin Abdul Aziz Shah'],
            ['LP04', 'Politeknik Mersing'],
            ['LP05', 'Politeknik Ibrahim Sultan'],
            ['LR01', 'Republic Polytechnic'],
            ['LR02', 'Rialair Ltd'],
            ['LS01', 'Seawig Technologies PTE LTD'],
            ['LS02', 'Shaanxi Polytechnic Institute'],
            ['LS03', 'Shipload Group (PT SMPL)'],
            ['LS04', 'Singapore Polytechnic'],
            ['LS05', 'Solustar Pte Ltd'],
            ['LS06', 'Shanxi Construction Investment Group Co., Ltd'],
            ['LU01', 'Universitas Teknikal Malaysia Melaka'],
            ['LU02', 'Universitas Sabah Malaysia'],
            ['LU03', 'Universite Polytechnique Hauts-De-France (UPHF)'],
            ['LU04', 'Universiti Poly-Tech Malaysia'],
            ['LU05', 'Universiti Tun Hussein Onn Malaysia'],
            ['LV01', 'VICTORIA AVIATION ACADEMY'],
            ['LW01', 'Wufeng University'],
            ['M01', 'Masyarakat Akuakultur Indonesia'],
            ['M02', 'Majelis Ulama Indonesia Kota Batam'],
            ['N01', 'NBO Bebras Indonesia'],
            ['N02', 'NVidia Indonesia'],
            ['NO01', 'Notaris dan PPAT Didik Sulistyono, SH., M.Kn'],
            ['P01', 'Pemerintah Kabupaten Kepulauan Anambas'],
            ['P02', 'Pemerintah Kabupaten Lingga'],
            ['P03', 'Pemerintah Kota Batam'],
            ['P04', 'Pemerintah Kota Pekanbaru'],
            ['P05', 'Pemerintah Provinsi Aceh'],
            ['P06', 'Pemerintah Provinsi Kepulauan Riau'],
            ['P07', 'Pengurus Cabang Nadhatul Ulama (PCNU) Kota Batam'],
            ['P08', 'Perpustakaan Kantor Perwakilan Bank Indonesia Provinsi Kepulauan Riau'],
            ['P09', 'Perpustakaan Nasional Republik Indonesia'],
            ['P10', 'Perpustakaan Universitas International Batam'],
            ['P11', 'Persatuan Insinyur Indonesia (PII)'],
            ['P12', 'Persatuan Insinyur Indonesia (PII) Cabang Kota Batam'],
            ['P13', 'Perwakilan Badan Kependudukan Dan Keluarga Berencana Nasional Provinsi Kepri'],
            ['PL01', 'Politeknik APP Jakarta'],
            ['PL02', 'Politeknik ATI Makassar'],
            ['PL03', 'Politeknik Caltex Riau'],
            ['PL04', 'Politeknik Dewantara'],
            ['PL05', 'Politeknik Gajah Tunggal'],
            ['PL06', 'Politeknik Industri Logam Morowali'],
            ['PL07', 'Politeknik Industri Petrokimia Banten (PIPB)'],
            ['PL08', 'Politeknik Jambi'],
            ['PL09', 'Politeknik Kampar'],
            ['PL10', 'Politeknik Manufaktur Astra'],
            ['PL11', 'Politeknik Negeri Bandung'],
            ['PL12', 'Politeknik Negeri Banyuwangi'],
            ['PL13', 'Politeknik Negeri Bengkalis'],
            ['PL14', 'Politeknik Negeri Jakarta'],
            ['PL15', 'Politeknik Negeri Ketapang'],
            ['PL16', 'Politeknik Negeri Lhokseumawe'],
            ['PL17', 'Politeknik Negeri Madura'],
            ['PL18', 'Politeknik Negeri Malang'],
            ['PL19', 'Politeknik Negeri Medan'],
            ['PL20', 'Politeknik Negeri Padang'],
            ['PL21', 'Politeknik Negeri Pontianak'],
            ['PL22', 'Politeknik Negeri Sambas'],
            ['PL23', 'Politeknik Pariwisata Batam'],
            ['PL24', 'Politeknik Penerbangan Palembang'],
            ['PL25', 'Politeknik Pertanian Negeri Pangkajene'],
            ['PL26', 'Politeknik Pertanian Negeri Payakumbuh (Politani)'],
            ['PL27', 'Politeknik STMI Jakarta'],
            ['PL28', 'Politeknik Negeri Sriwijaya'],
            ['PP01', 'Pondok Pesantren Baitul Quran Batam'],
            ['PP02', 'Pondok Pesantren Ulul Ilmi Cendekia'],
            ['PTA01', 'PT Ade Mestakung Abadi'],
            ['PTA02', 'PT Aero Terra Indonesia'],
            ['PTA03', 'PT Agry Meugah Mandiri'],
            ['PTA04', 'PT Agung Muda Berkarya'],
            ['PTA05', 'PT Amreta Teknik Internasional'],
            ['PTA06', 'PT Aneka Sakti Bakti (Asaba)'],
            ['PTA07', 'PT Anya Sumber Rezeki (Daing Mas Griya Jamu Herbal & Coffee Shop)'],
            ['PTA08', 'PT APINDO'],
            ['PTA09', 'PT Archasindo'],
            ['PTA10', 'PT Arunika Terang Indonesia'],
            ['PTA11', 'PT Asia Citra Riau Property'],
            ['PTA12', 'PT Asia NDT Laboratories And Supplies'],
            ['PTA13', 'PT Astra Group Pekanbaru'],
            ['PTB01', 'PT Bandara Internasional Batam'],
            ['PTB02', 'PT Barelang Glassindo'],
            ['PTB03', 'PT Batam Multimedia Televisi'],
            ['PTB04', 'PT Batamindo Investment Cakrawala'],
            ['PTB05', 'PT Bentera Tabang Nusantara (Beta)'],
            ['PTB06', 'PT Berlian Dumai Logistics (Bdl) Cabang Batam'],
            ['PTB07', 'PT Bintan Alumina Indonesia'],
            ['PTB08', 'PT Bintan Inti Industrial Estate'],
            ['PTB09', 'PT Bintang Sukses Globalindo'],
            ['PTB10', 'PT Biro Klasifikasi Indonesia (Persero)'],
            ['PTB11', 'PT Bizlink Technology Indonesia'],
            ['PTB12', 'PT Budaya Digital Indonesia'],
            ['PTB13', 'PT Bias Surya Teknologi'],
            ['PTB14', 'PT Bina Teladan Mandiri'],
            ['PTC01', 'PT Cameron Systems'],
            ['PTC02', 'PT Caterpillar Indonesia Batam'],
            ['PTC03', 'PT Ciba Vision Batam'],
            ['PTC04', 'PT Cicor Panatec'],
            ['PTC05', 'PT Cladtek Bi-Metal Manufacturing'],
            ['PTC06', 'PT Comac Multi Industri'],
            ['PTC07', 'PT Cyber Edu Inkor (CEI)'],
            ['PTC08', 'PT Cambridge Industrial Batam'],
            ['PTD01', 'PT Dast In'],
            ['PTD02', 'PT Desa Air Cargo Batam'],
            ['PTD03', 'PT Dok Warisan Pertama'],
            ['PTD04', 'PT Dora Bisnis Konsultindo'],
            ['PTD05', 'PT Dreams Studio Indonesia'],
            ['PTD06', 'PT Dredolf Indonesia'],
            ['PTD07', 'PT Duta Perjalanan Wisata (My Bus Batam)'],
            ['PTE01', 'PT Etowa Packaging Indonesia'],
            ['PTE02', 'PT Excelitas Technologies Batam'],
            ['PTE03', 'PT Explora Prima'],
            ['PTE04', 'PT ELESKA IATKI'],
            ['PTF01', 'PT Fast Precision Manufacturing Indonesia'],
            ['PTF02', 'PT Free The Sea'],
            ['PTF03', 'PT Frisidea Tech Indonesia'],
            ['PTG01', 'PT Garuda Maintenance Facility Aero Asia Tbk'],
            ['PTG02', 'PT GDS Indonesia Group (Day One)'],
            ['PTG03', 'PT Global Data Inspirasi'],
            ['PTG04', 'PT Golden Batam Raya'],
            ['PTG05', 'PT Goto Gojek Tokopedia Tbk'],
            ['PTG06', 'PT Galang Bumi Industri'],
            ['PTH01', 'PT Halcom Inovasi Teknologi'],
            ['PTH02', 'PT Hanika Indonesia Berkah'],
            ['PTH03', 'PT Hawila Adhi Perkasa'],
            ['PTH04', 'PT Hoki Surya Ningrat (Snipeyes)'],
            ['PTI01', 'PT Ilmubox Pengetahuan Internasional'],
            ['PTI02', 'PT Indina Industri Indonesia'],
            ['PTI03', 'PT Indoproff Group'],
            ['PTI04', 'PT Inspektindo Sinergi Persada'],
            ['PTI05', 'PT Inixindo Widya Iswara Nusantara'],
            ['PTI06', 'PT INOVASI KECERDASAN BUATAN (PLATTER)'],
            ['PTJ01', 'PT Jasa Raharja'],
            ['PTJ02', 'PT Jati Bening Indonesia'],
            ['PTJ03', 'PT Jati Sukses Mandiri'],
            ['PTK01', 'PT Kagungan Jaya Sukses (Id.Project)'],
            ['PTK02', 'PT Karbon Multindo Utama'],
            ['PTK03', 'PT Karya Teknik Utama (KTU Shipyard)'],
            ['PTK04', 'PT Kemina Dunia Medika'],
            ['PTK05', 'PT Kinema Systrans Multimedia (Infinite Learning)'],
            ['PTK06', 'PT Kinobi Technologies Indonesia'],
            ['PTK07', 'PT Kitong Karya Inovasi'],
            ['PTK08', 'PT Konsultindo Artha Persada'],
            ['PTK09', 'PT Kriya Kreatif Anugerah (Movingthings Production)'],
            ['PTK10', 'PT Kuarta Powerindo Perkasa'],
            ['PTK11', 'PT Kumala Indonesia Shipyard'],
            ['PTK12', 'PT Karya Muria Niaga'],
            ['PTL01', 'PT Lancang Kuning Sukses'],
            ['PTL02', 'PT Laras Adhi Praya'],
            ['PTL03', 'PT Lentera Segara Indonesia'],
            ['PTL04', 'PT Lifelong Learning'],
            ['PTL05', 'PT Lippo Karawaci, Tbk'],
            ['PTM01', 'PT Macan Teknologi Asia'],
            ['PTM02', 'PT Makmur Elok Graha'],
            ['PTM03', 'PT Marine Propulsion Solution'],
            ['PTM04', 'PT Markija Berdaya Bersama'],
            ['PTM05', 'PT Markplus Indonesia'],
            ['PTM06', 'PT McDermott Indonesia'],
            ['PTM07', 'PT Medco Power Indonesia'],
            ['PTM08', 'PT Media Promosi Batam/Batam Promotion'],
            ['PTM09', 'PT Mekar Bersama Dua Bintang'],
            ['PTM10', 'PT Mes Teknologi Indonesia'],
            ['PTM11', 'PT Meta Citra Indonesia'],
            ['PTM12', 'PT Mitra Integritas Indonesia (FolxCode)'],
            ['PTM13', 'PT Mosha Sinalsal Solusi'],
            ['PTM14', 'PT Multi Mitra Guna'],
            ['PTM15', 'PT Multi Prima Daya Perkasa'],
            ['PTM16', 'PT Mitra Persada Sejati'],
            ['PTM17', 'PT MITRA KARYA SARANA'],
            ['PTN01', 'PT Najah Karya Muda'],
            ['PTN02', 'PT Nirwana Turisindo'],
            ['PTN03', 'PT Nusatama Properta Panbil'],
            ['PTN04', 'PT Negeri Seni Teknologi (SecLab Indonesia)'],
            ['PTP01', 'PT Pakartek Engineering'],
            ['PTP02', 'PT Panasonic Industrial Devices Batam'],
            ['PTP03', 'PT Panca Anugrah Sakti'],
            ['PTP04', 'PT Panca Prima Prestasi'],
            ['PTP05', 'PT Pangeran Pekanbaru Hotel'],
            ['PTP06', 'PT Patlite Indonesia'],
            ['PTP07', 'PT Patria Maritim Perkasa'],
            ['PTP08', 'PT PCI Elektronik Internasional'],
            ['PTP09', 'PT Pelayanan Energi Batam'],
            ['PTP10', 'PT Pelayanan Listrik Nasional Batam'],
            ['PTP11', 'PT Pertama Pacific Shipyard'],
            ['PTP12', 'PT Philips Industries Batam'],
            ['PTP13', 'PT Pinnacle Afa Edukasi'],
            ['PTP14', 'PT PJB Ubjom PLTU Tenayan (PT Pembangkitan Jawa-Bali (PJB) melalui Unit Bisnis Jasa O&M (UBJOM) PLTU Tenayan)'],
            ['PTP15', 'PT Pobos Pradi Jaya (Pobo Soccer)'],
            ['PTP16', 'PT Pratama Indomitra Konsultan'],
            ['PTP17', 'PT Prima Bersama Berkat (Bosshire)'],
            ['PTP18', 'PT Purwa Satmitra Teknologi'],
            ['PTP19', 'PT Pusaka Talenta Nusantara'],
            ['PTP20', 'PT PASIFIK ASIA SOLUSION'],
            ['PTR01', 'PT Raditya Alkademi Digital'],
            ['PTR02', 'PT Rahayu Agro Makmur'],
            ['PTR03', 'PT Rajawali Angkasa Showroom (RAM Showroom)'],
            ['PTR04', 'PT Resous Expet Developmen (RED)'],
            ['PTR05', 'PT Revolusi Cita Edukasi'],
            ['PTR06', 'PT RGroup Indonesia'],
            ['PTR07', 'PT Riau Andalan Pulp And Paper (RAPP)'],
            ['PTR08', 'PT Riau Media Televisi (RTV)'],
            ['PTR09', 'PT Riau Perkasa Energi'],
            ['PTR10', 'PT Rigspek Perkasa'],
            ['PTR11', 'PT Risea EBT Solusi'],
            ['PTR12', 'PT Riseal Propulsion Indonesia'],
            ['PTS01', 'PT Sago Design Engineering'],
            ['PTS02', 'PT Sanindo Multi Tekno'],
            ['PTS03', 'PT Sarana Pembangunan Pekanbaru (SPP)'],
            ['PTS04', 'PT Sat Nusapersada Tbk'],
            ['PTS05', 'PT Satukelas Adhyapana Nusantara'],
            ['PTS06', 'PT Schneider Electric Manufacturing Batam'],
            ['PTS07', 'PT Schneider Indonesia'],
            ['PTS08', 'PT Seacad Technologies Indonesia'],
            ['PTS09', 'PT Sembada Bina Pratama'],
            ['PTS10', 'PT Servotech Indonesia'],
            ['PTS11', 'PT Shimano Batam'],
            ['PTS12', 'PT Siix Electronics Indonesia'],
            ['PTS13', 'PT Simatelex Manufactory Batam'],
            ['PTS14', 'PT Sindo Teknologi Industri'],
            ['PTS15', 'PT SMOE Indonesia'],
            ['PTS16', 'PT Solusi Kampus Indonesia'],
            ['PTS17', 'PT Kawan Lama Solusi'],
            ['PTS18', 'PT Statistik Hasil Pencarian'],
            ['PTS19', 'PT Sucofindo Batam'],
            ['PTS20', 'PT Sumitomo Wiring Systems Batam Indonesia'],
            ['PTS21', 'PT Sytham Pilar Utama'],
            ['PTS22', 'PT Supra Teknologi Plastik'],
            ['PTS23', 'PT Swanten Karya Adicita (BatamTech)'],
            ['PTS24', 'PT Swastika Lumintu Amerta'],
            ['PTS25', 'PT SIDMA TEKNIK SOLUSI INDONESIA'],
            ['PTT01', 'PT Tambang Indonesia Merdeka'],
            ['PTT02', 'PT Tanto Berjaya Pointel'],
            ['PTT03', 'PT TDK Electronics Indonesia'],
            ['PTT04', 'PT Technomedia Interkom Cemerlang'],
            ['PTT05', 'PT Teknologi Adaptif Indonesia'],
            ['PTT06', 'PT Teknologi Data Infrastruktur (Neutra DC)'],
            ['PTT07', 'PT Telekomunikasi Selular (Telkomsel)'],
            ['PTT08', 'PT Tiga Digdaya Abadi'],
            ['PTT09', 'PT TJK Power'],
            ['PTT10', 'PT Torani Pandu Indonesia'],
            ['PTT11', 'PT Trans Marine Opportunity'],
            ['PTT12', 'PT Tri Multi Bahtera'],
            ['PTT13', 'PT Trimatra Daya Sarana'],
            ['PTT14', 'PT Tec Indonesia'],
            ['PTU01', 'PT Ultima Tekno Solusindo'],
            ['PTU02', 'PT United Sindo Perkasa'],
            ['PTV01', 'PT VME Process'],
            ['PTV02', 'PT Vortex Energy Batam'],
            ['PTV03', 'PT V-Tech Teknologi Indonesia'],
            ['PTV04', 'PT Volex Indonesia'],
            ['PTW01', 'PT Weina Light Indonesia'],
            ['PTW02', 'PT WIK Far East'],
            ['PTY01', 'PT Yogya Presisi Teknikatama Industri (PT YPTI)'],
            ['PTY02', 'PT Yageo TMSS Indonesia'],
            ['PTZ01', 'PT Zetta Nusantara Studio (Zettamind Studio)'],
            ['PTZ02', 'PT Zona Asia Forwarding'],
            ['PTZ03', 'PT ZIERA GLOBAL TEKNIK'],
            ['PU01', 'Pusat Kolaborasi Desain Chip Indonesia'],
            ['PU02', 'Pusat Layanan Pembiayaan Pendidikan, Kementerian Pendidikan Dasar dan Menengah'],
            ['PU03', 'PUSAT PEMBIAYAAN DAN ASESMEN PENDIDIKAN TINGGI KEMENTERIAN PENDIDIKAN TINGGI, SAINS, DAN TEKNOLOGI'],
            ['PU04', 'Pusat Pengembangan Sumber Daya Manusia Perhubungan Udara Kementerian Perhubungan'],
            ['PU05', 'Puskesmas Baloi Permai'],
            ['R01', 'Rotary Club Of Batam'],
            ['RS01', 'Rumah Sakit Awal Bross Batam'],
            ['RS02', 'Rumah Sakit Budi Kemuliaan'],
            ['S01', 'SEAMOLEC'],
            ['S02', 'Stasiun Meteorologi Kelas I Hang Nadim Batam BMKG'],
            ['SA01', 'Sekolah SMA IT Fajar Ilahi Bengkong'],
            ['SA02', 'Sekolah SMA Negeri 9 Batam'],
            ['SK01', 'Sekolah SMK 1 Negeri Batam'],
            ['SK02', 'Sekolah SMK Dirgantara Riau'],
            ['SK03', 'Sekolah SMK Kal-1 Surabaya'],
            ['SK04', 'Sekolah SMK Maarif Nu Batam'],
            ['SK05', 'Sekolah SMK Muhammadiyah Batam'],
            ['SK06', 'Sekolah SMK Multistudi High School Batam'],
            ['SK07', 'Sekolah SMK Negeri 1 Bintan Utara'],
            ['SK08', 'Sekolah SMK Negeri 1 Bunguran Timur Utara'],
            ['SK09', 'Sekolah SMK Negeri 1 Garut'],
            ['SK10', 'Sekolah SMK Negeri 1 Tanjung Pinang'],
            ['SK11', 'Sekolah SMK Negeri 10 Batam'],
            ['SK12', 'Sekolah SMK Negeri 3 Batam'],
            ['SK13', 'Sekolah SMK Negeri 4 Malang'],
            ['SK14', 'Sekolah SMK Negeri 4 Tanjung Pinang'],
            ['SK15', 'Sekolah SMK Negeri 5 Batam'],
            ['SK16', 'Sekolah SMK Negeri 6 Batam'],
            ['SK17', 'Sekolah SMK Negeri 7 Batam'],
            ['SK18', 'Sekolah SMK Negeri 9 Batam'],
            ['SK19', 'Sekolah SMK Negeri Kundur'],
            ['SK20', 'Sekolah SMK Penerbangan Batam'],
            ['SK21', 'Sekolah SMK Penerbangan Nasional Batam'],
            ['SK22', 'Sekolah SMK Penerbangan SPN Dirgantara Batam'],
            ['SK23', 'Sekolah SMK Pertiwi Batam'],
            ['SK24', 'Sekolah SMKs Aljabar Batam'],
            ['SK25', 'Sekolah SMKs Kartini Batam'],
            ['SL01', 'Sekolah Luar Biasa Putra Kami'],
            ['ST01', 'Sekolah Tinggi Ilmu Ekonomi Bentara Persada'],
            ['T01', 'Tri Hita Karana Centre'],
            ['T02', 'Trust Academic Solutions'],
            ['TT01', 'Tour & Travel Fuji Tour Batam'],
            ['TT02', 'Tour And Travel Fantastik'],
            ['UM01', 'Danara Utama Katering'],
            ['UM02', 'DDshop'],
            ['UM03', 'Itaewon K-Boba'],
            ['UM04', 'Jom Tea'],
            ['UM05', 'M3D Barbershop'],
            ['UM06', 'Mimishandmade'],
            ['UM07', 'Nada Food'],
            ['UM08', 'Ntj Creative'],
            ['UM09', 'Oxyra Water'],
            ['UM10', 'PSG Corp'],
            ['UM11', 'Resto Baabaa Kambing'],
            ['UM12', 'Roti Hap'],
            ['UM13', 'Sarrab Pizza And Burger Station'],
            ['UM14', 'Widi Utami Wedding Organizer'],
            ['UM15', 'Angkat Koper'],
            ['UM16', 'Applenesia - Apple Servis Center Specialist'],
            ['UM17', 'Avocado Muslimah Wear'],
            ['UM18', 'Ayam Geprek Juara Aviari'],
            ['UN01', 'Universitas Hang Tuah Pekanbaru'],
            ['UN02', 'Universitas Ibnu Sina Batam'],
            ['UN03', 'Universitas Indonesia'],
            ['UN04', 'Universitas Maritim Raja Ali Haji'],
            ['UN05', 'Universitas Batam'],
            ['UN06', 'Universitas Brawijaya'],
            ['UN07', 'Universitas Darussalam Gontor'],
            ['UN08', 'Universitas Dinamika'],
            ['UN09', 'Universitas Diponegoro'],
            ['UN10', 'Universitas Gadjah Mada'],
            ['UN11', 'Universitas Internasional Batam'],
            ['UN12', 'Universitas Islam Negeri Sjech M. Djamil Djambek Bukittinggi'],
            ['UN13', 'Universitas Jember'],
            ['UN14', 'Universitas Negeri Malang (UM)'],
            ['UN15', 'Universitas Negeri Padang'],
            ['UN16', 'Universitas Putera Batam (UPB)'],
            ['UN17', 'Universitas Riau'],
            ['UN18', 'Universitas Riau Kepulauan'],
            ['UN19', 'Universitas Sari Mutiara Indonesia'],
            ['UN20', 'Universitas Tanjung Pura'],
            ['UN21', 'Universitas Terbuka'],
            ['UN22', 'Universitas Universal'],
            ['UN23', 'Universitas Nusa Putra'],
            ['UN24', 'UNIVERSITAS NEGERI MEDAN'],
            ['UN25', 'Universitas Andalas'],
            ['UN26', 'UNIVERSITAS MARITIM RAJA ALI HAJI (UMRAH)'],
            ['Y01',  'Yuditha Prameswari, M.Psi., Psikolog'],
            ['YA01', 'Yayasan Bahasa Indonesia Australia/Indonesia Australia Language Foundation (Ialf)'],
            ['YA02', 'Yayasan Bina Teruna Indonesia Bumi Cendrawasih (Binterbusih) Semarang'],
            ['YA03', 'Yayasan Bintan Resort'],
            ['YA04', 'Yayasan Cinderella Indonesia'],
            ['YA05', 'Yayasan Embun Pelangi Kota Batam'],
            ['YA06', 'Yayasan Ikbal-M-Yos Batam'],
            ['YA07', 'Yayasan Logistik Indonesia'],
            ['YA08', 'Yayasan Prestasi Junior Gemilang Indonesia'],
            ['YA09', 'Yayasan Rumah Kreatif Bunda'],
            ['YA10', 'Yayasan Tiblat Istiqomah Al-Amin'],
            ['YA11', 'Yayasan Cipta Generasi Indonesia'],
        ];

        $updated = 0;
        $deleted = 0;
        $skipped = 0;

        foreach ($data as [$kode, $nama]) {
            $hasKode = MasterMitra::where('kode_mitra', $kode)->exists();

            $oldRecords = MasterMitra::whereNull('kode_mitra')
                ->whereRaw('LOWER(TRIM(nama_mitra)) = LOWER(TRIM(?))', [$nama])
                ->get();

            if ($oldRecords->isEmpty()) {
                $skipped++;
                continue;
            }

            if ($hasKode) {
                // Kode sudah ada di record seeder → hapus duplikat lama
                foreach ($oldRecords as $old) {
                    $old->delete();
                    $deleted++;
                }
            } else {
                // Belum ada kode → assign ke record lama yang pertama, hapus sisanya
                $first = $oldRecords->first();
                $first->update(['kode_mitra' => $kode]);
                $updated++;

                foreach ($oldRecords->skip(1) as $dup) {
                    $dup->delete();
                    $deleted++;
                }
            }
        }

        $this->command->info("Selesai: {$updated} record diberi kode, {$deleted} duplikat dihapus, {$skipped} nama tidak ditemukan.");
    }
}
